apiVersion: v1
kind: Service
metadata:
  name: shopkart-backend
  namespace: shopkart
  labels:
    app: shopkart-backend
spec:
  type: ClusterIP
  selector:
    app: shopkart-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
