apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopkart-postgres-data-manual
  namespace: shopkart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
