apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopkart-postgres
  namespace: shopkart
  labels:
    app: shopkart-postgres
spec:
  serviceName: shopkart-postgres
  replicas: 1
  selector:
    matchLabels:
      app: shopkart-postgres
  template:
    metadata:
      labels:
        app: shopkart-postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: shopkart
            - name: POSTGRES_USER
              value: shopkart_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopkart-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "shopkart_user", "-d", "shopkart"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "shopkart_user", "-d", "shopkart"]
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
