# ============================================================
# Standalone Grafana values (if you install grafana separately)
# ============================================================

adminUser: admin
adminPassword: prom-operator

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prom-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: shopkart
        orgId: 1
        folder: ShopKart
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/shopkart
