{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: shopkart-backend
  namespace: {{ include "shopkart.namespace" . }}
  labels:
    {{- include "shopkart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "shopkart.selectorLabels" (dict "component" "backend" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP
{{- end }}
